sudo: required
language: generic

services: 
  - docker 

before_install:
  - docker build -t mamclaughlin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mamclaughlin/docker-react npm run test -- --coverage
    